# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['broker:8080']

    metric_relabel_configs:
      # Relabel: topic=ztf_20180425_programid2 -> night=20180425, program=MSIP
      - source_labels: [ topic ]
        regex: "ztf_(\\d+)_.*"
        target_label: "night"
        replacement: "$1"
      - source_labels: [ topic ]
        regex: "ztf_\\d+_programid0"
        target_label: "program"
        replacement: "Commissioning"
      - source_labels: [ topic ]
        regex: "ztf_\\d+_programid1"
        target_label: "program"
        replacement: "MSIP"
      - source_labels: [ topic ]
        regex: "ztf_\\d+_programid2"
        target_label: "program"
        replacement: "ZTF"
      - source_labels: [ topic ]
        regex: "ztf_\\d+_programid3"
        target_label: "program"
        replacement: "CalTech"

  - job_name: 'mirrormaker'
    static_configs:
      - targets: ['broker:8081']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['broker:8082']

  - job_name: 'kafka-node'
    static_configs:
      - targets: ['broker:9100']

  - job_name: 'grafana-node'
    static_configs:
      - targets: ['localhost:9100']
