version: '3.1'

networks:
  default:
    external:
      name: ztf_broker

services:
  mirrormaker:
    image: confluentinc/cp-kafka:4.1.0
#    depends_on:
#      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=localhost:32181
      - KAFKA_HEAP_OPTS=-Xmx4G
    command: /usr/bin/kafka-mirror-maker --consumer.config /mnt/mm_consumer1.properties --producer.config /mnt/mm_producer1.properties --whitelist="^ztf.*1$$"
    volumes:
      - .:/mnt
